### ISSUE TITLE
Possible new data source: cell-to-cell interaction db?

### ISSUE THREAD

**Issue by karafecho** [RobokopU24/NewSourceProposals#10]
This issue is intended to document a potentially interesting data source that we may want to incorporate into ROBOKOP: [CCIDB]( https://pubmed.ncbi.nlm.nih.gov/37566630/). I don't have a clear use case in mind, but I stumbled on this resource and thought I'd alert folks to it.

**Comment by eKathleenCarter** [comment]
#35
