### ISSUE TITLE
Data Source: LINCS L1000 database

### ISSUE THREAD

**Issue by beasleyjonm** [RobokopU24/NewSourceProposals#42]
From the NIH website (https://lincsproject.org/LINCS/tools/workflows/find-the-best-place-to-obtain-the-lincs-l1000-data): 

"The LINCS L1000 project has collected gene expression profiles for thousands of perturbagens at a variety of time points, doses, and cell lines. A full list of the chemical and genetic perturbations used can be found on the [CLUE website](https://clue.io/) along with their descriptions."

**Comment by eKathleenCarter** [comment]
#3
