### ISSUE TITLE
SIGNOR

### ISSUE THREAD

**Issue by beasleyjonm** [RobokopU24/NewSourceProposals#46]
SIGNOR is a repository of manually annotated causal relationships between human proteins, chemicals of biological relevance, stimuli and phenotypes. The search field below allows users to access the entity page detailing all the causal relationships annotated to the query entity. SIGNOR also curates pathways that can be accessed by making choices in the drop down menu below. In addition SIGNOR offers advanced graph tools to explore the human cell network.

**Comment by beasleyjonm** [comment]
SIGNOR will require manual mapping of relationships and mechanisms to Biolink predicates. I started the process in the [Google Sheet](https://docs.google.com/spreadsheets/d/10dNKwUiGdHH_FSBhHudxhBQ-FwDSr8rxFErlrX98hL0/edit?usp=sharing)

**Comment by eKathleenCarter** [comment]
@beasleyjonm please fill out a DMOG score sheet (the first page). We can add this as an agenda item to review tomorrow. We are moving toward a quarterly incorporation of sources after reviewing and scoring.

**Comment by beasleyjonm** [comment]
[SIGNOR_Purposed_DataManagementOversightScoring_v2.docx](https://github.com/RobokopU24/NewSourceProposals/files/15001230/SIGNOR_Purposed_DataManagementOversightScoring_v2.docx)
Here is the score sheet! Basically, I have a parser for this source ready to go, but not all of the nodes normalize and the infores catalog needs updated for this resource (I already submitted a PR to update infores).

**Comment by eKathleenCarter** [comment]
@beasleyjonm to quantify number of edges that can be mapped in NN and number of edges that do not yet have mapping

**Comment by beasleyjonm** [comment]
The nodes which fail to normalize are:
91 SIGNOR Protein Family nodes.
208 SIGNOR Phenotype nodes.
25 SIGNOR Stimuli nodes.
26 RNACENTRAL miRNA nodes.
8 PUBCHEM.COMPOUND nodes.
7 CHEBI compound nodes.
4 SID (Pubchem SIDs ?) nodes.

With strict conflation set to False, 28855 unique edges are created. Removing these un-normalized nodes, 25238 unique edges remain.
